### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by est7** [imageprocessor/cv4j#1]
tomain方法每次都要重新new，或许可以使用这个方法http://www.jcodecraeer.com/a/anzhuokaifa/androidkaifa/2015/0819/3327.html

**Comment by fengzhizi715** [comment]
hi @est7 ，可能我没有加注释的缘故，toMain()确实是要跟compose操作符配合使用的。
我在demo app里也是这样写的：）
还是非常感谢您！
