### ISSUE TITLE
I can not resolve cv4j in my project. Here is my build.gradle

### ISSUE THREAD

**Issue by assmdx** [imageprocessor/cv4j#16]
group 'com.assmdx'
version '1.0-SNAPSHOT'

apply plugin: 'java'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile "com.google.zxing:core:3.3.0"
    compile 'com.google.zxing:javase:3.3.0'
    compile 'com.cv4j:cv4j:0.1.2'
}

**Comment by fengzhizi715** [comment]
hi  @assmdx 

try this

repositories {
jcenter()
mavenCentral()
}

**Comment by assmdx** [comment]
Thank you! I have solved this problem by compiling your code to  a jar .
