### ISSUE TITLE
关于效率问题

### ISSUE THREAD

**Issue by EvilBT** [imageprocessor/cv4j#2]
我把人脸磨皮的那部分改用c实现，然后用jni调用，我打印了log看了一下人脸磨皮的时间，发现用java层的大概是700ms，而用c的话只需要30ms，如果在实际应用中，使用NDK会更好吧？

**Comment by gloomyfish** [comment]
thank you very much for your good feedback and suggestion

**Comment by fengzhizi715** [comment]
用ndk确实效率会更高，未来我们也可能会用ndk，也欢迎您来提交pr ：）

**Comment by EvilBT** [comment]
@fengzhizi715 嗯嗯，好的
