### ISSUE TITLE
Crash in cv4j demo app when on start MainActivity at 7.0 Android device

### ISSUE THREAD

**Issue by lgyjg** [imageprocessor/cv4j#4]
01-07 18:55:09.098  4361  4361 E AndroidRuntime: FATAL EXCEPTION: main
01-07 18:55:09.098  4361  4361 E AndroidRuntime: Process: com.cv4j.app, PID: 4361
01-07 18:55:09.098  4361  4361 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cv4j.app/com.cv4j.app.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.Toolbar.setNavigationOnClickListener(android.view.View$OnClickListener)' on a null object reference
01-07 18:55:09.098  4361  4361 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2678)
01-07 18:55:09.098  4361  4361 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2745)
01-07 18:55:09.098  4361  4361 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
01-07 18:55:09.098  4361  4361 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1484)
01-07 18:55:09.098  4361  4361 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-07 18:55:09.098  4361  4361 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
01-07 18:55:09.098  4361  4361 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6174)
01-07 18:55:09.098  4361  4361 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-07 18:55:09.098  4361  4361 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
01-07 18:55:09.098  4361  4361 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
01-07 18:55:09.098  4361  4361 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.Toolbar.setNavigationOnClickListener(android.view.View$OnClickListener)' on a null object reference
01-07 18:55:09.098  4361  4361 E AndroidRuntime: 	at com.cv4j.app.activity.MainActivity.initToolbar(MainActivity.java:89)
01-07 18:55:09.098  4361  4361 E AndroidRuntime: 	at com.cv4j.app.activity.MainActivity.initViews(MainActivity.java:49)
01-07 18:55:09.098  4361  4361 E AndroidRuntime: 	at com.cv4j.app.activity.MainActivity.onCreate(MainActivity.java:44)
01-07 18:55:09.098  4361  4361 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6666)
01-07 18:55:09.098  4361  4361 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
01-07 18:55:09.098  4361  4361 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2631)
01-07 18:55:09.098  4361  4361 E AndroidRuntime: 	... 9 more

**Comment by lgyjg** [comment]
01-07 19:06:11.315  4803  4803 E AndroidRuntime: FATAL EXCEPTION: main
01-07 19:06:11.315  4803  4803 E AndroidRuntime: Process: com.cv4j.app, PID: 4803
01-07 19:06:11.315  4803  4803 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cv4j.app/com.cv4j.app.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.design.widget.NavigationView.setNavigationItemSelectedListener(android.support.design.widget.NavigationView$OnNavigationItemSelectedListener)' on a null object reference
01-07 19:06:11.315  4803  4803 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2678)
01-07 19:06:11.315  4803  4803 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2745)
01-07 19:06:11.315  4803  4803 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
01-07 19:06:11.315  4803  4803 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1484)
01-07 19:06:11.315  4803  4803 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-07 19:06:11.315  4803  4803 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
01-07 19:06:11.315  4803  4803 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6174)
01-07 19:06:11.315  4803  4803 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-07 19:06:11.315  4803  4803 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
01-07 19:06:11.315  4803  4803 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
01-07 19:06:11.315  4803  4803 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.design.widget.NavigationView.setNavigationItemSelectedListener(android.support.design.widget.NavigationView$OnNavigationItemSelectedListener)' on a null object reference
01-07 19:06:11.315  4803  4803 E AndroidRuntime: 	at com.cv4j.app.activity.MainActivity.initViews(MainActivity.java:50)
01-07 19:06:11.315  4803  4803 E AndroidRuntime: 	at com.cv4j.app.activity.MainActivity.onCreate(MainActivity.java:44)
01-07 19:06:11.315  4803  4803 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6666)
01-07 19:06:11.315  4803  4803 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
01-07 19:06:11.315  4803  4803 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2631)
01-07 19:06:11.315  4803  4803 E AndroidRuntime: 	... 9 more

**Comment by lgyjg** [comment]
这个问题是不是由于@InjectView(R.id.toolbar) 和 @InjectView(R.id.navigation_view)不生效导致的？

**Comment by fengzhizi715** [comment]
hi @lgyjg , 我刚刚创建了一个7.0的模拟器，运行一下没有问题。
你的手机型号是什么？我看看能否找到。
如果是@InjectView有问题的话，试一下findById()?

**Comment by lgyjg** [comment]
我使用的是还未上市的开发机测试的。这个信息暂时不能公布，我后续会修复这个问题

**Comment by lgyjg** [comment]
编译环境问题，暂时关闭
