### ISSUE TITLE
为项目创建Slack cv4j team group

### ISSUE THREAD

**Issue by lgyjg** [imageprocessor/cv4j#5]
@fengzhizi715 @gloomyfish : 
两位前辈，很高兴能了解到这个项目，虽然项目还在初始阶段，但是能够看得出来一定是一个很好的项目。我最近在拜读项目的代码。

为了方便关注者的沟通，我为项目创建了slack的team，Slack是一种在国外很成熟的团队沟通工具， 不知道这个项目是否想采用这样的沟通方式，因为QQ的局限实在太多了，很多人开发人员使用Linux，很少能够装QQ客户端，并且国外的开发人员也无法使用QQ沟通。因此，强烈建议使用Slack作为沟通工具。

以下是我创建的Slack Team：
https://cv4j.slack.com/

**Comment by fengzhizi715** [comment]
cool, 非常感谢。我已经加入slack，一会我让@gloomyfish 也加入：）

**Comment by lgyjg** [comment]
好的，多多指教
